#!/bin/bash
# Chmatak Ivan (c) 2014
# - regularly touch SCRATCHDIR of running jobs

export PATH=$PATH:/usr/sbin:/usr/bin:/opt/pbs/sbin:/opt/pbs/bin

MOMCTL="momctl"
PRINTJOB="printjob"

# determinine running jobs from momctl
JOBS=`$MOMCTL -q jobs 2>/dev/null`
if [ $? -ne 0 ]
then
	sleep 10
	JOBS=`$MOMCTL -q jobs 2>/dev/null`
	if [ $? -ne 0 ]
	then
		logger -p daemon.err -t scratch_cleanup "Could not get list of running jobs from momctl."
		exit 0
	fi
fi

# touch scratch directories
for i in `echo "$JOBS" |sed "s/.* 'jobs=//"| sed "s/'//"`
do
	# get SCRATCHDIR
	SCRATCHDIR=`$PRINTJOB /var/spool/pbs/mom_priv/jobs/$i.JB 2>/dev/null | sed -n 's;^Variable_List = .*SCRATCHDIR=\([^,]*\).*;\1;p'`
	if [ ! "$SCRATCHDIR" ]
	then
		# try old version
		SCRATCHDIR=`$PRINTJOB /var/spool/pbs/mom_priv/jobs/$i.JB 2>/dev/null | grep ^SCRATCHDIR=|sed 's/.*=//'`
	fi

	# check the consistency
	SCRATCH_BY_EXEC_TYPE=`$PRINTJOB /var/spool/pbs/mom_priv/jobs/$i.JB 2>/dev/null | sed -n 's/^exec_vnode =.*'$(hostname -s)'[^+]*scratch_\([^+=]\+\)=.*/\1/p'`
	SCRATCH_BY_EXEC_SIZE=`$PRINTJOB /var/spool/pbs/mom_priv/jobs/$i.JB 2>/dev/null | sed -n 's/^exec_vnode =.*'$(hostname -s)'[^+]*scratch_[^+=]\+=\([0-9]\+\).*/\1/p'`
	if [ "$SCRATCH_BY_EXEC_SIZE" ] && [ "$SCRATCH_BY_EXEC_SIZE" -gt "0" ] && [ ! "$SCRATCHDIR" ]
	then
		ERRORMSG="$i requests scratch $SCRATCH_BY_EXEC_TYPE on $(hostname -s) but SCRATCHDIR not set"
		logger -p daemon.err -t scratch_cleanup "$ERRORMSG"
	fi

	# touch the scratch
	[ "$SCRATCHDIR" ] && touch -c $SCRATCHDIR 2>/dev/null;
done
